accounts/urls.py
from django.urls import path
from .views import (
    register, login, logout, activate, profile,
    forgot_password, reset_password_validate, reset_password,
    MyOrdersView, edit_profile, change_password, order_detail)

app_name = 'account'
urlpatterns = [
    path('register/', register, name=("register_page")),
    path('login/', login, name=("login_page")),
    path('logout/', logout, name=("logout_page")),
    path('profile/', profile, name=("profile_page")),

    path('forgot-password/', forgot_password, name=("forgot_password_page")),
    path('reset-password/', reset_password, name=("reset_password_page")),
    path('activate/<uidb64>/<token>/', activate, name=("activate_page")),
    path('reset-password-validate/<uidb64>/<token>/',
         reset_password_validate, name=("reset_password_validate_page")),

    path('my_orders/', MyOrdersView.as_view(), name='my_orders_page'),
    path('edit_profile/', edit_profile, name='edit_profile_page'),
    path('change_password/', change_password, name='change_password_page'),
    path('order_detail/<int:order_id>/',
         order_detail, name='order_detail_page'),

]

carts/urls.py
from django.urls import path
from .views import CartView, remove_cart, delete_cart_item, CheckoutView

app_name = 'cart'
urlpatterns = [
    path('', CartView.as_view(), name='cart_page'),
    path('add_to_cart/<int:product_id>/',
         CartView.as_view(), name='add_to_cart_page'),
    path('remove_from_cart/<int:product_id>/<int:cart_item_id>/',
         remove_cart, name='remove_from_cart_page'),
    path('delete_cart_item/<int:product_id>/<int:cart_item_id>/',
         delete_cart_item, name='delete_cart_item_page'),

    path('checkout/', CheckoutView.as_view(), name='checkout_page')
]

connect/urls.py
from django.urls import path
from . import views

app_name = 'connect'
urlpatterns = [
    path('contact/', views.ContactView.as_view(), name='contact'),
    # path('about/', views.AboutView.as_view(), name='about'),
    path('creators/', views.CreatorView.as_view(), name='creators'),
]

like/urls.py
from django.urls import path
from .views import LikeItemView

app_name = 'like'

urlpatterns = [
    path('like/<int:product_id>/', LikeItemView.as_view(), name='like_item'),
]

online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from category.views import BaseView

from azbankgateways.urls import az_bank_gateways_urls

admin.autodiscover()

# app_name = 'online_shop'
urlpatterns = [
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    # path('securelogin/', admin.site.urls),
    path('admin/', admin.site.urls),

    path('', BaseView.as_view(), name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('account/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('connect/', include('connect.urls', namespace='connect')),
    path('discount/', include('discount.urls')),
    path('coupons/', include('coupons.urls')),
    path('like/', include('like.urls')),


    path("bankgateways/", az_bank_gateways_urls()),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
{% load static %}
<!-- Footer Start -->
 <Style>
  .icon {
    min-width: 50px;
    border-radius: 20px;
    height: 40px;
  }
  
 </style>
<footer>
  <div class="container-fluid bg-dark text-light mt-5 pt-5">
    <div class="row px-xl-5 pt-5" style='direction: ltr !important;'>
      <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5" style='direction: rtl !important;'>
        <h5 class="text-light text-uppercase mb-4">ارتباط با ما</h5>
        <p class="mb-4">در صورت هرگونه سوال و پیشنهاد، با ما در ارتباط باشید.</p>
        <div  style='direction: ltr !important;'>
            <div class="mb-2" dir="ltr" style="display: flex; align-items: center;">
              <i class="fas fa-map-marker-alt text-primary mr-3"></i>
              <div style="direction: rtl !important;">گلستان، کلاله</div>
            </div>
          <p class="mb-2">
            <i class="fas fa-envelope text-primary mr-3"></i> hameddjf33@gmail.com
          </p>
          <p class="mb-0">
            <i class="fas fa-phone-alt text-primary mr-3"></i>+98 09931835803
          </p>
        </div>
      </div>
      <div class="col-lg-8 col-md-12" style='direction: rtl !important;'>
        <div class="row">
          <div class="col-md-4 mb-5">
            <h5 class="text-light text-uppercase mb-4">خبرنامه</h5>
            <p>با عضویت در خبرنامه از تخفیف‌ها و محصولات جدید مطلع شوید.</p>
            <form action="">
              <div class="input-group">
                <input type="email" class="form-control" placeholder="آدرس ایمیل" />
                <div class="input-group-append">
                  <a href="{% url 'account:register_page' %}" class="btn btn-primary">عضویت</a>
                </div>
              </div>
            </form>
            <h6 class="text-light text-uppercase mt-4 mb-3">دنبال کنید :</h6>
            <div class="d-flex">
              {% comment %} <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
              <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
              <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
              <a class="btn btn-primary btn-square" href="#"><i class="fab fa-instagram"></i></a> {% endcomment %}

              <a class="btn btn-primary btn-square mr-2 icon" href="https://t.me/BN2_hm" >تلگرام</a>
              <a class="btn btn-primary btn-square mr-2 icon" href="https://www.linkedin.com/in/hamed-moradi-aa8698304/" >لینکدین</a>
              <a class="btn btn-primary btn-square mr-2 icon" href="mailto:{{ creator.email }}" >ایمیل</a>

            </div>
          </div>
          <div class="col-md-4 mb-5">
            <h5 class="text-light text-uppercase mb-4">دسته‌بندی‌ها</h5>
            <div class="d-flex flex-column justify-content-start">
              <a class="text-light mb-2" href="{% url 'connect:creators' %}"><i class="fa fa-angle-right mr-2"></i> سازنده </a>
              <a class="text-light mb-2" href="{% url "home" %}"><i class="fa fa-angle-right mr-2"></i> صفحه اصلی </a>
              <a class="text-light mb-2" href="{% url 'store'  %}"><i class="fa fa-angle-right mr-2"></i> فروشگاه </a>
              <a class="text-light mb-2" href="{% url "cart:cart_page" %}"><i class="fa fa-angle-right mr-2"></i> سبد خرید </a>
              <a class="text-light" href="{% url 'connect:contact' %}"><i class="fa fa-angle-right mr-2"></i> تماس با ما </a>
              {% comment %} <a class="text-light mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>جزئیات محصول</a> {% endcomment %}
              {% comment %} <a class="text-light mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>پرداخت</a> {% endcomment %}
              <a class="text-light" href="{% url "account:profile_page" %}"><i class="fa fa-angle-right mr-2"></i> پروفایل</a>
              <a class="text-light mb-2" href="{% url "account:login_page" %}"><i class="fa fa-angle-right mr-2"></i> ورود</a>
              <a class="text-light mb-2" href="{% url "account:register_page" %}"><i class="fa fa-angle-right mr-2"></i> ثبت نام </a>

            </div>
          </div>
          <div class="col-md-4 mb-5">
            <h5 class="text-light text-uppercase mb-4">حساب کاربری</h5>
            <div class="d-flex flex-column justify-content-start">
              <a class="text-light mb-2" href="{% url 'connect:creators' %}"><i class="fa fa-angle-right mr-2"></i> سازنده </a>
              <a class="text-light mb-2" href="{% url "home" %}"><i class="fa fa-angle-right mr-2"></i> صفحه اصلی </a>
              <a class="text-light mb-2" href="{% url 'store'  %}"><i class="fa fa-angle-right mr-2"></i> فروشگاه </a>
              {% comment %} <a class="text-light mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>جزئیات محصول</a> {% endcomment %}
              <a class="text-light mb-2" href="{% url "cart:cart_page" %}"><i class="fa fa-angle-right mr-2"></i> سبد خرید </a>
              {% comment %} <a class="text-light mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>پرداخت</a> {% endcomment %}
              <a class="text-light" href="{% url 'connect:contact' %}"><i class="fa fa-angle-right mr-2"></i> تماس با ما </a>
              <a class="text-light" href="{% url "account:profile_page" %}"><i class="fa fa-angle-right mr-2"></i> پروفایل</a>
              <a class="text-light" href="{% url "account:login_page" %}"><i class="fa fa-angle-right mr-2"></i> ورود</a>
              <a class="text-light" href="{% url "account:register_page" %}"><i class="fa fa-angle-right mr-2"></i> ثبت نام </a>
            </div>
          </div>
          
        </div>
      </div>
    </div>
    <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
      <div class="col-md-6 px-xl-0">
        <p class="mb-md-0 text-center text-md-left text-light">
          &copy; <a class="text-primary" href="#">نام دامنه</a>. همه حقوق محفوظ است. طراحی شده توسط
          <a class="text-primary" href="https://htmlcodex.com">hameddjf</a>
        </p>
      </div>
      <div class="col-md-6 px-xl-0 text-center text-md-right">
        <img class="img-fluid" src="{% static "img/payments.png" %}" alt="" />
      </div>
    </div>
  </div>
</footer><!-- Footer End -->
{% comment %} برای زمانی ک نخوام کراسل عکس رو استفاده کنم بجاش لیست کامل عکسارو همراه عکس اصلی ببینم {% endcomment %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
  $(document).ready(function(){
    $('.thumb a').click(function(e){
      e.preventDefault();
      var newImageSrc = $(this).attr("href");
      // تغییر دادن منبع تصویر اصلی به منبع تصویر کلیک شده
      $('#product-carousel .carousel-inner .carousel-item img').attr('src', newImageSrc);
      // حذف کلاس active از تمام تصاویر کاروسل
      $('#product-carousel .carousel-inner .carousel-item').removeClass('active');
      // افزودن کلاس active به اولین تصویر کاروسل که همیشه تصویر اصلی است
      $('#product-carousel .carousel-inner .carousel-item:first').addClass('active');
    })
  })
</script>
</body>
</html>

templates/includes/navbar.html
{% load custom_tags %}

<style>
  .dropdown-menu .dropdown-item {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    direction: rtr; 
    text-align: center;
    display: block;
    width: 100%;
  }
  
  .dropdown-submenu .dropdown-menu {
    direction: rtr; /* برای اطمینان از راست به چپ نگه داشتن زیر منو */
    top: 0;
    left: 100%;
    margin-top: -1rem;
    margin-left: 0.5rem;
    display: none;
    background-color: #f8f9fa;
    padding: 0.5rem 0;
    border-radius: 0.25rem;
    box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15);
    max-height: 300px;
    overflow: auto;
  }
  .dropdown-item {
    padding: 0.5rem 1rem;
    color: #495057;
    transition: background-color 0.15s ease-in-out;
  }
  
  .dropdown-item:hover {
    background-color: #e9ecef;
    color: #16181b;
  }
  
  .dropdown-submenu .dropdown-item.dropdown-toggle::after {
    float: right;
    margin-top: 0.5rem;
    border-top: 0.3em solid transparent;
    border-right: 0;
    border-bottom: 0.3em solid transparent;
    border-left: 0.3em solid;
  }

  .dropdown-submenu:hover > .dropdown-menu {
    display: block;
  }

  .dropdown:hover > .dropdown-menu {
    display: block;
  }

</style>
<!-- Topbar Start -->
<div class="container-fluid">
  <div class="row bg-secondary py-1 px-xl-5">
    <!--                <div class="col-lg-6 d-none d-lg-block">
                  <div class="d-inline-flex align-items-center h-100">
                      <a class="text-body mr-3" href="">About</a>
                      <a class="text-body mr-3" href="">Contact</a>
                      <a class="text-body mr-3" href="">Help</a>
                      <a class="text-body mr-3" href="">FAQs</a>
                  </div>
              </div>                -->
    <div class="col-lg-6 text-center text-lg-right">
      {% comment %} <div class="d-inline-flex align-items-center">
        <div class="btn-group">
          <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">حساب من</button>
          <div class="dropdown-menu dropdown-menu-right">

            <a href="{% url 'account:login_page' %}">
            <button class="dropdown-item" type="button">ورود</button>
          </a>

            <a href="{% url 'account:register_page' %}">
              <button class="dropdown-item" type="button">ثبت نام</button>
            </a>

          </div>
        </div>
        <div class="btn-group mx-2">
          <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">واحد پولی</button>
          <div class="dropdown-menu dropdown-menu-right">
            <button class="dropdown-item" type="button">USD</button>
            <button class="dropdown-item" type="button">EUR</button>
            <button class="dropdown-item" type="button">IRR</button>
          </div>
        </div> 
        <div class="btn-group">
          <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">زبان</button>
          <div class="dropdown-menu dropdown-menu-right">
            <button class="dropdown-item" type="button">FA</button>
            <button class="dropdown-item" type="button">EN</button>
            <!-- <button class="dropdown-item" type="button">RU</button> -->
          </div>
        </div>
      </div> {% endcomment %}
      <div class="d-inline-flex align-items-center d-block d-lg-none">
        <!--                <a href="" class="btn px-0 ml-2">
                          <i class="fas fa-heart text-dark"></i>
                          <span class="badge text-dark border border-dark rounded-circle"
                              style="padding-bottom: 2px;">0</span>
                      </a>                -->
        <a href="" class="btn px-0 ml-2">
          <i class="fas fa-shopping-cart text-dark"></i>
          <span class="badge text-dark border border-dark rounded-circle" style="padding-bottom: 2px;">0</span>
        </a>
      </div>
    </div>
  </div>
  <div class="row align-items-center bg-light py-3 px-xl-5 d-none d-lg-flex">
    <div class="col-lg-4">
      <!--                <a href="" class="text-decoration-none">
                      <span class="h1 text-uppercase text-primary bg-dark px-2">Multi</span>
                      <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1">Shop</span>
                  </a>                -->
    </div>
    <div class="col-lg-4 col-6 text-left">
      <form action="{% url "search_page" %}" class='search' method='GET'>
        <div class="input-group">
          <input type="text" class="form-control" placeholder="جستجوی محصول" name='keyword' />
          <div class="input-group-append">
            <button type='submit' class="input-group-text bg-transparent text-primary"><i class="fa fa-search" ></i></button>
          </div>
        </div>
      </form>
    </div>
    <div class="col-lg-4 col-6 text-right">
      <p class="m-0">خدمات مشتری</p>
      <h5 class="m-0">+98 09931835803</h5>
    </div>
  </div>
</div>
<!-- Topbar End -->

<!-- Navbar Start -->
<div class="container-fluid bg-dark mb-30">
  <div class="row px-xl-5">
    <div class="col-lg-3 d-none d-lg-block">
      <a class="btn d-flex align-items-center justify-content-end bg-primary w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; padding: 0 30px;">
        <i class="fa fa-bars text-dark mr-auto"></i>
        <h6 class="text-dark m-0">دسته بندی ها</h6>
        <i class="fa fa-angle-down text-dark ml-2"></i>
      </a>
      <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 999;">
        <div class="navbar-nav w-100">

          {% comment %} listing category {% endcomment %}
          <a href="{% url "store" %}" class="nav-item nav-link">تمام محصولات</a>
          {% for category in links %}
            {% if category.parent is None %}
              <div class="nav-item dropdown dropright">
                <a href="{{ category.get_absolute_url }}" class="nav-link dropdown-toggle" data-toggle="dropdown">{{ category.title }} <i class="fa fa-angle-right float-right mt-1"></i></a>
                <div class="dropdown-menu position-absolute rounded-0 border-0 m-0" style="width: 220px; direction: rtl;">
                  {% for child_category in category.children.all %}
                    {% if child_category.children.all %}
                      <div class="dropdown-submenu">
                        <a href="{{ child_category.get_absolute_url }}" class="dropdown-item dropdown-toggle">{{ child_category.title }} <i class="fa fa-angle-right float-right"></i></a>
                        <div class="dropdown-menu position-absolute rounded-0 border-0 m-0" style="width: 180px; left: 100%; top: 0;">
                          {% for grandchild_category in child_category.children.all %}
                            <a href="{{ grandchild_category.get_absolute_url }}" class="dropdown-item">{{ grandchild_category.title }}</a>
                          {% endfor %}
                        </div>
                      </div>
                    {% else %}
                      <a href="{{ child_category.get_absolute_url }}" class="dropdown-item">{{ child_category.title }}</a>
                    {% endif %}
                  {% endfor %}
                </div>
              </div>
            {% endif %}
          {% endfor %}

        </div>
      </nav>
    </div>
    <div class="col-lg-9">
      <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
        <a href="" class="text-decoration-none d-block d-lg-none">
          <span class="h1 text-uppercase text-dark bg-light px-2">فروشگاه</span>
          <span class="h1 text-uppercase text-light bg-primary px-2 ml-n1">انلاین</span>
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
          <div class="navbar-nav mr-auto py-0">
            <a href="{% url "home" %}" class="nav-item nav-link active">خانه</a>
            <div class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">صفحات <i class="fa fa-angle-down mt-1"></i></a>
              <div class="dropdown-menu bg-primary rounded-0 border-0 m-0">
                <a href="{% url "account:profile_page" %}" class="dropdown-item">پروفایل</a>
                <a href="{% url "cart:cart_page" %}" class="dropdown-item">سبد خرید</a>
                <a href="{% url "cart:checkout_page" %}" class="dropdown-item">بررسی</a>
                <a href="{% url 'store'  %}" class="dropdown-item">محصولات</a>
                <a href="{% url "account:login_page" %}" class="dropdown-item">ورود</a>
                <a href="{% url "account:register_page" %}" class="dropdown-item">ثبت نام</a>
              </div>
            </div>
            <a href="{% url 'connect:contact' %}" class="nav-item nav-link">تماس با ما</a>
            <a href="{% url 'connect:creators' %}" class="nav-item nav-link">سازنده</a>
            {% comment %} <a href="#" class="nav-item nav-link">درباره ما</a> {% endcomment %}
            {% comment %} <a href="#" class="nav-item nav-link">جستجو</a> {% endcomment %}
            {% comment %} <a href="#" class="nav-item nav-link">وبلاگ</a> {% endcomment %}
          </div>
          <div class="navbar-nav ml-auto py-0 d-none d-lg-block">
            {% if user.is_authenticated %}
            <a href="{% url 'account:logout_page' %}">
                {% if user.get_full_name %}
                    {{ user.get_full_name }}
                {% else %}
                    {{ user.username }}
                {% endif %}
            </a>
            {% else %}
                <a href="{% url 'account:login_page' %}" class="btn px-0 ml-3">
                    <i class="fas fa-sign-in-alt text-primary"></i>
                </a>
            {% endif %}
            <a href="{% url 'cart:cart_page' %}" class="btn px-0 ml-3">
              <i class="fas fa-shopping-cart text-primary"></i>
              <span class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">{{cart_count}}</span>
            </a>
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>
<!-- Navbar End -->

templates/includes/profile_sidebar.html
<aside class="col-md-3">
    <!--   SIDEBAR   -->
    <ul class="list-group">
      <a class="list-group-item {% if '/accounts/' == request.path %}active{% endif %}" href="{% url 'account:profile_page' %}"> داشبورد </a>
      <a class="list-group-item {% if '/my_orders/' in request.path %}active{% endif %}" href="{% url 'account:my_orders_page' %}"> سفارشات من </a>
      <a class="list-group-item {% if '/edit_profile/' in request.path %}active{% endif %}" href="{% url 'account:edit_profile_page' %}"> ویرایش پروفایل </a>
      <a class="list-group-item {% if '/change_password/' in request.path %}active{% endif %}" href="{% url 'account:change_password_page' %}"> تغییر رمز عبور </a>
    </ul>
    <br>
    <a class="btn btn-light btn-block" href="{% url 'account:logout_page' %}"> <i class="fa fa-power-off"></i> <span class="text">خروج</span> </a>
    <!--   SIDEBAR .//END   -->
</aside>