carts/urls.py
from django.urls import path
from .views import CartView, remove_cart, delete_cart_item, CheckoutView

app_name = 'cart'
urlpatterns = [
    path('', CartView.as_view(), name='cart_page'),
    path('add_to_cart/<int:product_id>/',
         CartView.as_view(), name='add_to_cart_page'),
    path('remove_from_cart/<int:product_id>/<int:cart_item_id>/',
         remove_cart, name='remove_from_cart_page'),
    path('delete_cart_item/<int:product_id>/<int:cart_item_id>/',
         delete_cart_item, name='delete_cart_item_page'),

    path('checkout/', CheckoutView.as_view(), name='checkout_page')
]

coupons/urls.py
from django.urls import path
from .views import CouponApplyView

app_name = 'coupons'
urlpatterns = [
    path('apply-coupon/', CouponApplyView.as_view(), name='apply_coupon'),
]

like/urls.py
from django.urls import path
from .views import LikeItemView

app_name = 'like'

urlpatterns = [
    path('like/<int:product_id>/', LikeItemView.as_view(), name='like_item'),
]

online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from category.views import BaseView

from azbankgateways.urls import az_bank_gateways_urls

admin.autodiscover()

# app_name = 'online_shop'
urlpatterns = [
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    # path('securelogin/', admin.site.urls),
    path('admin/', admin.site.urls),

    path('', BaseView.as_view(), name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('account/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('connect/', include('connect.urls', namespace='connect')),
    path('discount/', include('discount.urls')),
    path('coupons/', include('coupons.urls')),
    path('like/', include('like.urls')),


    path("bankgateways/", az_bank_gateways_urls()),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import StoreView, ProductDetailView, search, submit_review

urlpatterns = [
    path('', StoreView.as_view(), name='store'),
    path('category/<slug:category_slug>/',
         StoreView.as_view(), name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/',
         ProductDetailView.as_view(), name='products_detail'),

    path('search/', search, name='search_page'),

    path('submit_review/<int:product_id>/',
         submit_review, name='submit_review_page'),

]

carts/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from store.models import Product, Variation
# Create your models here.


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = ("سبد خرید")
        verbose_name_plural = ("سبد های خرید")

    def __str__(self):
        return self.cart_id

    # def get_absolute_url(self):
    #     return reverse("_detail", kwargs={"pk": self.pk})


class CartItem(models.Model):
    user = models.ForeignKey(
        "accounts.Account", verbose_name=_("کاربر"),
        on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    coupon = models.ForeignKey(
        'coupons.Coupon', on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    variations = models.ManyToManyField(
        Variation, verbose_name=_("واریانت ها"), blank=True)

    def sub_total(self):
        if self.product.discount_price:
            return self.product.discount_price * self.quantity
        else:
            return self.product.price * self.quantity

    class Meta:
        verbose_name = ("کالا سبد خرید")
        verbose_name_plural = ("کالاهای سبد خرید")

    def __str__(self):
        return str(self.product)

store/forms.py
from django import forms
from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

carts/views.py
import requests
import logging
import re

from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import View
from django.db.models.query_utils import Q
from django.views.generic import TemplateView
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator


from .models import Cart, CartItem

from store.models import Product, Variation
from orders.forms import OrderForm
# Create your views here.


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


class CartView(View):
    def get(self, request, product_id=None):
        try:
            tax = 0
            grand_total = 0
            total = 0
            quantity = 0
            if request.user.is_authenticated:
                cart_items = CartItem.objects.filter(
                    user=request.user, is_active=True)
            else:
                try:
                    cart = Cart.objects.get(cart_id=_cart_id(request))
                    cart_items = CartItem.objects.filter(
                        cart=cart, is_active=True)
                except Cart.DoesNotExist:
                    cart = Cart.objects.create(cart_id=_cart_id(request))
                    cart_items = []
            for cart_item in cart_items:
                total += (cart_item.product.discount_price *
                          cart_item.quantity if cart_item.product.discount_price else cart_item.product.price * cart_item.quantity)
                quantity += cart_item.quantity
            tax = (2 * total) / 100
            grand_total = total + tax

            context = {
                'total': total,
                'quantity': quantity,
                'cart_items': cart_items,
                'tax': tax,
                'grand_total': grand_total,
            }
            return render(request, 'store/cart.html', context)
        except Exception as e:
            # Log the exception or handle it in some other way
            print(f"Error in CartView.get: {e}")
            return render(request, 'store/cart.html', {
                'total': 0,
                'quantity': 0,
                'cart_items': [],
                'tax': 0,
                'grand_total': 0,
            })

    def post(self, request, product_id):
        current_user = request.user
        product = get_object_or_404(Product, pk=product_id)

        quantity = int(request.POST.get('quantity', 1))
        # if the user is authenticated
        if current_user.is_authenticated:
            product_variation = []
            if request.method == "POST":
                for item in request.POST:
                    try:
                        variation = Variation.objects.get(
                            variation_category__iexact=item,
                            variation_value__iexact=request.POST[item],
                            variation_products=product
                        )
                        product_variation.append(variation)
                    except Variation.DoesNotExist:
                        pass

            is_cart_item_exists = CartItem.objects.filter(
                product=product, user=current_user, variations__in=product_variation).exists()

            if is_cart_item_exists:
                cart_item = CartItem.objects.filter(
                    product=product, user=current_user, variations__in=product_variation)
                # existing variations --> database
                # current variations --> product_variation
                # item id --> database
                existing_variation_list = []
                id = []
                for item in cart_item:
                    existing_variation = item.variations.all()
                    existing_variation_list.append(list(existing_variation))
                    id.append(item.id)

                if product_variation in existing_variation_list:
                    # increase cart item quantity
                    index = existing_variation_list.index(product_variation)
                    item_id = id[index]
                    item = CartItem.objects.get(id=item_id)
                    item.quantity += quantity
                    item.save()
                else:
                    cart_item = CartItem.objects.get(
                        product=product, user=current_user, variations__in=product_variation)
                    cart_item.variations.set(product_variation)
                    cart_item.quantity += quantity
                    cart_item.save()
            else:
                cart_item = CartItem.objects.create(
                    product=product,
                    quantity=quantity,
                    user=current_user,
                )
                cart_item.variations.set(product_variation)
                cart_item.save()
            return redirect('cart:cart_page')
        # if user is not authenticated
        else:
            product_variation = []
            if request.method == "POST":
                for item in request.POST:
                    try:
                        variation = Variation.objects.get(
                            variation_category__iexact=item,
                            variation_value__iexact=request.POST[item],
                            variation_products=product
                        )
                        product_variation.append(variation)
                    except Variation.DoesNotExist:
                        pass

            try:
                # get the cart using the cart_id present in the session
                cart = Cart.objects.get(cart_id=self._cart_id(request))
            except Cart.DoesNotExist:
                cart = Cart.objects.create(
                    cart_id=self._cart_id(request)
                )
            cart.save()
            is_cart_item_exists = CartItem.objects.filter(
                product=product, cart=cart, variations__in=product_variation).exists()

            if is_cart_item_exists:
                cart_item = CartItem.objects.filter(
                    product=product, cart=cart, variations__in=product_variation)
                # existing variations --> database
                # current variations --> product_variation
                # item id --> database
                existing_variation_list = []
                id = []
                for item in cart_item:
                    existing_variation = item.variations.all()
                    existing_variation_list.append(list(existing_variation))
                    id.append(item.id)

                if product_variation in existing_variation_list:
                    # increase cart item quantity
                    index = existing_variation_list.index(product_variation)
                    item_id = id[index]
                    item = CartItem.objects.get(id=item_id)
                    item.quantity += 1
                    item.save()
                else:
                    cart_item = CartItem.objects.get(
                        product=product, cart=cart, variations__in=product_variation)
                    cart_item.variations.set(product_variation)
                    cart_item.quantity += 1
                    cart_item.save()
            else:
                cart_item = CartItem.objects.create(
                    product=product,
                    quantity=1,
                    cart=cart,
                )
                cart_item.variations.set(product_variation)
                cart_item.save()
            return redirect('cart:cart_page')
# private function


def remove_cart(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(
                product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(
                product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except Cart.DoesNotExist:
        pass
    return redirect('cart:cart_page')


def delete_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(
            product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(
            product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart:cart_page')


@method_decorator(login_required(login_url='account:login_page'), name='dispatch')
class CheckoutView(TemplateView):
    template_name = 'store/checkout.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get states from the API
        states_response = requests.get(
            "https://iran-locations-api.ir/api/v1/fa/states")
        states = states_response.json()
        context['states'] = states

        # Get cities based on selected state
        if 'state' in self.request.GET:
            state_name = self.request.GET.get('state')
            cities_response = requests.get(
                f"https://iran-locations-api.ir/api/v1/fa/cities?state={state_name}")
            cities = cities_response.json()
            logging.info(f"Cities: {cities}")
        elif 'state_id' in self.request.GET:
            state_id = self.request.GET.get('state_id')
            cities_response = requests.get(

templates/store/cart.html
{% extends "base.html" %}
{% load static %}
{% load custom_tags %}
{% load coupon_utils %}

{% block main %}

<style>
  .mb-5, .my-5 {
    direction: rtl;
  }

  .colorful:nth-child(odd) {
    color: dodgerblue;
    padding-left: 25px;
  }
  img {
    vertical-align: middle;
    border-style: none;
    float: left;
  }
  
  .colorful:nth-child(even) {
      color: coral;
  }
</style>
    <!-- Cart Start -->
    <div class="container-fluid">

      {% if not cart_items %}

        <h2 class='text-center rtl'>. سبد خرید شما خالیست </h2>
        </br>
        <div class='text-center'>
          <a href='{% url "store" %}' class='btn btn-primary' > ادامه خرید</a>
        </div>

    {% else %}

      <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
          <table class="table table-light table-borderless table-hover text-center mb-0">

            <thead class="thead-dark">
              <tr>
                <th>محصولات</th>
                <th>قیمت</th>
                <th>تعداد</th>
                <th>قیمت کل</th>
                <th>حذف</th>
              </tr>
            </thead>

            <tbody class="align-middle">

              {% for cart_item in cart_items %}
                  <tr>
                    <td class="align-middle">
                      <img src="{{cart_item.product.image.url}}" alt="" style="width: 50px;" /> 
                      <figcaption class='info'>
                        <a href='{{ cart_item.product.get_url }}' class='text-muted small'>
                          <strong class="colorful">{{cart_item.product.title}}</strong>
                        </a>
                        <p class='text-muted small'>
                          {% if cart_item.variations.all %}
                            {% for item in cart_item.variations.all %}
                                {{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }}<br>
                            {% endfor %}
                          {% endif %}
                        </p>
                      </figcaption>
                    </td>
                    {% if cart_item.product.discount == 0 %}
                        <td class="align-middle">{{cart_item.product.price|format_price}}</td>
                    {% else %}
                        <td class="align-middle">{{cart_item.product.discount_price|format_price}}</td>
                    {% endif %}
                    <td class="align-middle">
                      {% comment %}  ی باگ میخورد ک برداشتمش ت دکمه بعلاوه quantity بخاطر کلاس  {% endcomment %}
                      <div class="col"> 
                        <div class="input-group mx-auto" style="width: 100px;" >
                            <div class="input-group-btn">
                            <a href="{% url 'cart:remove_from_cart_page' cart_item.product.id cart_item.id %}" class="btn btn-sm btn-primary btn-minus" type="button"> <i class="fa fa-minus"></i> </a>
                            </div>
                            <input type="text" class="form-control form-control-sm bg-secondary border-0 text-center"  value="{{cart_item.quantity}}">
                            <div class="input-group-btn">
                                <form action="{% url 'cart:add_to_cart_page' cart_item.product.id  %}" method='POST'>
                                    {% csrf_token %}
                                    {% for item in cart_item.variations.all  %}
                                        <input type='hidden' name="{{item.variation_category |  lower}}" value="{{item.variation_value | capfirst}}">
                                    {% endfor %}
                                    <button class="btn btn-sm btn-primary btn-plus" type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>
                                </form>
                            </div>
                        </div> <!-- input-group.// -->

                    </td>
                    <td class="align-middle">{{cart_item.sub_total|format_price}}</td>
                    <td class="align-middle">
                      <a href='{% url "cart:delete_cart_item_page" cart_item.product.id cart_item.id %}' onclick="return confirm('ایا مطمعئن هستین میخواهید این محصول را حذف کنید؟')" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a>
                    </td>
                  </tr>
              {% endfor %}

            </tbody>
          </table>
        </div>
        <div class="col-lg-4">
          <form id="coupon-form"  action="{% url 'coupons:apply_coupon' %}" method="post">
            <div class="input-group">
                <input type="text" name="coupon_code" class="form-control border-0 p-4 floatformat : right" placeholder="کد کوپن" required />
                <div class="input-group-append">
                    {% for cart_item in cart_items %}
                      <input type="hidden" name="cart_items[]" value="{{ cart_item.id }}">
                    {% endfor %}
                    {% csrf_token %}
                      <button class="btn btn-sm btn-primary btn-plus" type="submit">اعمال کوپن</button>
                </div>
            </div>
        </form>

          <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">خلاصه سبد خرید</span></h5>
          <div class="bg-light p-30 mb-5">
            <div class="border-bottom pb-2">
                {% comment %} {% if 'coupon_code' in request.session %}
                <div class="d-flex justify-content-between mb-3">
                    <h6>قیمت کل </h6>
                    <h5>{{ total|format_price }}</h5>

                </div>
                <div class="d-flex justify-content-between">
                    <h6 class="font-weight-medium" >تخفیف کوپن: </h6>
                    <h6> {{ request.session.coupon_code }} ({{ request.session.discount_percent }}%)</h6>
                </div>
                {% else %}
                <div class="d-flex justify-content-between mb-3">
                    <h6>قیمت کل</h6>
                    <h5>{{ total|format_price }}</h5>
                </div>
                {% endif %}
                <div class="d-flex justify-content-between">
                    <h6 class="font-weight-medium">مالیات</h6>
                    <h6 class="font-weight-medium">{{ tax|format_price }}</h6>
                </div>
                <div class="d-flex justify-content-between">
                    <h5> مجموع کل قابل پرداخت</h5>
                  {% if 'coupon_code' in request.session %}
                    <h6>{{ request.session.total_price_with_coupon|format_price }}</h6>
                  {% else %}
                    <h5>{{ grand_total|format_price }}</h5>
                  {% endif %} {% endcomment %}
                  <div class="d-flex justify-content-between mb-3">
                      <h6>قیمت کل</h6>
                      <h5>{{ total|format_price }}</h5>
                  </div>
                  <div class="d-flex justify-content-between">
                      <h6 class="font-weight-medium">مالیات</h6>
                      <h6 class="font-weight-medium">{{ tax|format_price }}</h6>
                  </div>
                  <div class="d-flex justify-content-between">
                      <h5> مجموع کل قابل پرداخت</h5>
                      <h5>{{ grand_total|format_price }}</h5>
                </div>
            </div>
            <div class="pt-2">
                <a href="{% url 'cart:checkout_page' %}" class="btn btn-block btn-primary font-weight-bold my-3 py-3">ادامه به صفحه پرداخت</a>
                <a href="{% url 'store' %}" class="btn btn-block btn-success font-weight-bold my-3 py-3">ادامه خرید</a>
            </div>
        </div>
      </div>

    {% endif %}

    </div>
    <!-- Cart End -->
{% endblock main %}